#pragma config(Sensor, dgtl1,  TrackerL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  TrackerR,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  CatBtn,         sensorTouch)
#pragma config(Motor,  port1,           Catapult1,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LB1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LB2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LB3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           IntakeL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           IntakeR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RB1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RB2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RB3,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Catapult2,     tmotorVex393_HBridge, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "betterthanv5.h"
#include "autonstuff.h"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
  SensorValue[TrackerL] = 0;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  pewpew(RIGHT);
	//park(LEFT);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

  while (true)
  {
  	//REMEMBER TO UNCOMMENT
   	startTask(catapult);
		startTask(differential);

	for(;;){

		//if(vexRT[Btn7U]) pewplus(RIGHT);
		//if(vexRT[Btn7L]) pewpark(RIGHT);
		if(vexRT[Btn7D] && time1[T1]>300){
			mode = -mode;
			clearTimer(T1);
		}

		//Drive
		leftBase = mode * vexRT[Ch3] + vexRT[Ch1];
		rightBase = mode * vexRT[Ch3] - vexRT[Ch1];
		motor[LB1] = leftBase;
		motor[LB2] = leftBase;
		motor[LB3] = leftBase;
		motor[RB1] = rightBase;
		motor[RB2] = rightBase;
		motor[RB3] = rightBase;
	}
  }
}
